@startuml
'https://plantuml.com/class-diagram


interface AgenticService
interface SequentialAgentService
class SequentialAgentServiceImpl
interface LoopAgentService
class LoopAgentServiceImpl
interface ParallelAgentService
class ParallelAgentServiceImpl
interface ConditionalAgentService
class ConditionalAgentServiceImpl
interface PlannerBasedService
class PlannerBasedServiceImpl
abstract class AbstractServiceBuilder

AgenticService <|-- SequentialAgentService
AgenticService <|-- LoopAgentService
AgenticService <|-- ParallelAgentService
AgenticService <|-- ConditionalAgentService
AgenticService <|-- PlannerBasedService

SequentialAgentService <|.. SequentialAgentServiceImpl
LoopAgentService <|.. LoopAgentServiceImpl
ParallelAgentService <|.. ParallelAgentServiceImpl
ConditionalAgentService <|.. ConditionalAgentServiceImpl
PlannerBasedService <|.. PlannerBasedServiceImpl

SequentialAgentServiceImpl --|> AbstractServiceBuilder
LoopAgentServiceImpl --|> AbstractServiceBuilder
ParallelAgentServiceImpl --|> AbstractServiceBuilder
ConditionalAgentServiceImpl --|> AbstractServiceBuilder
PlannerBasedServiceImpl --|> AbstractServiceBuilder


@enduml