@startuml
'https://plantuml.com/class-diagram

interface AiServiceEvent
class AiServiceStartedEvent
class AiServiceResponseReceivedEvent
class AiServiceErrorEvent
class AiServiceCompletedEvent
class ToolExecutedEvent
class InputGuardrailExecutedEvent
class OutputGuardrailExecutedEvent

AiServiceEvent <|-- AiServiceStartedEvent
AiServiceEvent <|-- AiServiceResponseReceivedEvent
AiServiceEvent <|-- AiServiceErrorEvent
AiServiceEvent <|-- AiServiceCompletedEvent
AiServiceEvent <|-- ToolExecutedEvent
AiServiceEvent <|-- InputGuardrailExecutedEvent
AiServiceEvent <|-- OutputGuardrailExecutedEvent


@enduml