@startuml
'https://plantuml.com/class-diagram


interface ContentRetriever
class WebSearchContentRetriever
class EmbeddingStoreContentRetriever

ContentRetriever <|-- WebSearchContentRetriever
ContentRetriever <|-- EmbeddingStoreContentRetriever


@enduml