@startuml
'https://plantuml.com/class-diagram


interface QueryTransformer
class DefaultQueryTransformer
class CompressingQueryTransformer
class ExpandingQueryTransformer

QueryTransformer <|-- DefaultQueryTransformer
QueryTransformer <|-- CompressingQueryTransformer
QueryTransformer <|-- ExpandingQueryTransformer


@enduml